### ISSUE TITLE
Texture Generation produces incorrect results in linear colorspace

### ISSUE THREAD

**Issue by hybridherbst** [needle-tools/procedural-stochastic-texturing#1]
Hi @thomasdeliot,

would be great if you could chime in to bring this research back to life – seems while everything's working great in Gamma space, the generation and texture usage currently breaks in Linear space (also on the original repo).

The generated data kinda looks correct, so maybe just some of the internal values are wrong that are passed to the shader?

In linear space:
![image](https://user-images.githubusercontent.com/2693840/104592386-6f61be00-566e-11eb-9014-4485025c3ef8.png)

In gamma space:
![image](https://user-images.githubusercontent.com/2693840/104592486-96b88b00-566e-11eb-8f6f-047e4ba72499.png)

**Comment by ghost** [comment]
Hi !

I just spent some time trying out your project. Firstly thanks for doing this! I tried out both the builtin code and shadergraph node from your OpenUPM package and didn't get this issue, it worked both in gamma and linear space for me.
However it's necessary (unfortunately) to regenerate the data : for builtin, this requires deleting both generated textures in the assets and re-applying in the material inspector window, and for shadergraph re-applying in the ProceduralTexture2D inspector window.

Also for the shadergraph version, everytime something is changed in the ProceduralTexture2D asset (input texture or color mode, etc) any shadergraph that uses this asset won't be updated automatically, as there was (at the time at least) no way for custom ScriptableObjects to trigger an update of the asset database system monitored by shadergraph. So after switching colour space, you need to re-generate the ProceduralTexture2D, then unlink & relink the ProceduralTexture2D Asset node in the graph.

Can you detail what were your steps to make the issue appear if it's not related to this ?

**Comment by hybridherbst** [comment]
Hi, thanks for chiming in!

I tried again, but I still get the same results.
I'm experiencing this on URP and HDRP, Unity 2020.2. When switching to Linear and following the above steps I always end up with incorrect / wrongly colored results.

Steps to reproduce:

- clone this repository
- open the development/2020.2-URP Unity Project which has everything set up
- open the MultiTexture scene (in Packages/Stochastic Texturing Test Assets/)
- regenerate procedural asset + re-connect/re-save shadergraph
- note that this looks correct
- switch to linear color space (note that scene looks brighter, kind of expected)
- regenerate procedural asset + re-connect/re-save shadergraph
- note that colors are off (red without normal, black with normal)

![image](https://user-images.githubusercontent.com/2693840/105359826-2bcffc80-5bf8-11eb-805f-a62c1a834eed.png)

**Comment by ghost** [comment]
Fixed in https://github.com/needle-tools/procedural-stochastic-texturing/commit/eddb2dfcca99b2a1738e088e73666b657c1285a5
